/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.service.user;

import cn.vansky.auth.bo.user.User;
import cn.vansky.auth.dto.user.UserDto;
import cn.vansky.framework.core.service.GenericService;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_user
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
public interface UserService extends GenericService<User, Integer> {

    List<UserDto> findPageList(Map<String, Object> map);

    User findUserByMap(User user);
}