/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.service.impl.userMenu;

import cn.vansky.auth.bo.userMenu.UserMenu;
import cn.vansky.auth.dao.userMenu.UserMenuDao;
import cn.vansky.auth.service.userMenu.UserMenuService;
import cn.vansky.framework.core.dao.SqlMapDao;
import cn.vansky.framework.core.service.GenericSqlMapServiceImpl;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_user_menu
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
@Service("userMenuService")
public class UserMenuServiceImpl extends GenericSqlMapServiceImpl<UserMenu, Integer> implements UserMenuService {
    @Resource(name = "userMenuDao")
    private UserMenuDao userMenuDao;

    @Override
    public SqlMapDao<UserMenu, Integer> getDao() {
        return userMenuDao;
    }

    @Override
    public void delMenu(Map<String, Object> params) {
        userMenuDao.delMenu(params);
    }
}