/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.dao.role;

import cn.vansky.auth.bo.role.Role;
import cn.vansky.auth.dto.role.RoleDto;
import cn.vansky.framework.core.dao.SqlMapDao;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_role
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
public interface RoleDao extends SqlMapDao<Role, Integer> {

    public List<RoleDto> findPageList(Map<String, Object> params);
}