/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.service.impl.user;

import cn.vansky.auth.bo.user.User;
import cn.vansky.auth.dao.user.UserDao;
import cn.vansky.auth.dto.user.UserDto;
import cn.vansky.auth.service.user.UserService;
import cn.vansky.framework.core.dao.SqlMapDao;
import cn.vansky.framework.core.service.GenericSqlMapServiceImpl;
import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_user
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
@Service("userService")
public class UserServiceImpl extends GenericSqlMapServiceImpl<User, Integer> implements UserService {
    @Resource(name = "userDao")
    private UserDao userDao;

    @Override
    public SqlMapDao<User, Integer> getDao() {
        return userDao;
    }

    @Override
    public List<UserDto> findPageList(Map<String, Object> params) {
        return userDao.findPageList(params);
    }

    @Override
    public User findUserByMap(User user) {
        return userDao.findUserByMap(user);
    }
}