/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.service.impl.roleMenu;

import cn.vansky.auth.bo.roleMenu.RoleMenu;
import cn.vansky.auth.dao.roleMenu.RoleMenuDao;
import cn.vansky.auth.service.roleMenu.RoleMenuService;
import cn.vansky.framework.core.dao.SqlMapDao;
import cn.vansky.framework.core.service.GenericSqlMapServiceImpl;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_role_menu
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
@Service("roleMenuService")
public class RoleMenuServiceImpl extends GenericSqlMapServiceImpl<RoleMenu, Integer> implements RoleMenuService {
    @Resource(name = "roleMenuDao")
    private RoleMenuDao roleMenuDao;

    @Override
    public SqlMapDao<RoleMenu, Integer> getDao() {
        return roleMenuDao;
    }

    @Override
    public void delMenu(Map<String, Object> params) {
        roleMenuDao.delMenu(params);
    }
}