/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.dao.user;

import cn.vansky.auth.bo.user.User;
import cn.vansky.auth.dto.user.UserDto;
import cn.vansky.framework.core.dao.DaoMapper;
import cn.vansky.framework.core.orm.mybatis.annotation.SqlMapper;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_user
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
@SqlMapper
public interface UserMapper extends DaoMapper<User, Integer> {

    void deleteByIds(List<Integer> list);

    List<UserDto> findPageList(Map<String, Object> params);

    User findUserByMap(User user);
}