/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.dao.menu;

import cn.vansky.auth.bo.menu.Menu;
import cn.vansky.auth.dto.menu.MenuAuthDto;
import cn.vansky.auth.dto.menu.MenuDto;
import cn.vansky.framework.core.dao.DaoMapper;
import cn.vansky.framework.core.orm.mybatis.annotation.SqlMapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_menu
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
@SqlMapper
public interface MenuMapper extends DaoMapper<Menu, Integer> {

    public List<MenuDto> findPageList(Map<String, Object> params);

    List<MenuAuthDto> findRoleMenu(Map<String, Object> params);

    List<Menu> findByRoleId(@Param("roleId")Integer roleId, @Param("systemId") Integer systemId);

    List<Menu> findByUserId(@Param("userId") Integer userId, @Param("systemId") Integer systemId);
}