/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.service.impl.role;

import cn.vansky.auth.bo.role.Role;
import cn.vansky.auth.dao.role.RoleDao;
import cn.vansky.auth.dto.role.RoleDto;
import cn.vansky.auth.service.role.RoleService;
import cn.vansky.framework.core.dao.SqlMapDao;
import cn.vansky.framework.core.service.GenericSqlMapServiceImpl;
import javax.annotation.Resource;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_role
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
@Service("roleService")
public class RoleServiceImpl extends GenericSqlMapServiceImpl<Role, Integer> implements RoleService {
    @Resource(name = "roleDao")
    private RoleDao roleDao;

    @Override
    public SqlMapDao<Role, Integer> getDao() {
        return roleDao;
    }

    @Override
    public List<RoleDto> findPageList(Map<String, Object> params) {
        return roleDao.findPageList(params);
    }
}