/*
 * Copyright (C) 2015 CK, Inc. All Rights Reserved.
 */

package cn.vansky.auth.service.menu;

import cn.vansky.auth.bo.menu.Menu;
import cn.vansky.auth.dto.menu.MenuAuthDto;
import cn.vansky.auth.dto.menu.MenuDto;
import cn.vansky.framework.core.service.GenericService;
import cn.vansky.framework.core.web.filter.auth.AuthWrapper;

import java.util.List;
import java.util.Map;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_menu
 *
 * @mbggenerated 2015-09-05 14:06:23
 */
public interface MenuService extends GenericService<Menu, Integer> {

    List<MenuDto> findPageList(Map<String, Object> params);

    List<MenuAuthDto> findRoleMenu(Map<String, Object> params);

    AuthWrapper findAuthWrapper(Integer userId, Integer systemId);
}